// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv1YsA6GxeW4GRAUxVJ0EThvfoh9wwNSw',
    appId: '1:306144619621:web:f2873e4333110fadb5ea8c',
    messagingSenderId: '306144619621',
    projectId: 'ezblog-e46a4',
    authDomain: 'ezblog-e46a4.firebaseapp.com',
    storageBucket: 'ezblog-e46a4.appspot.com',
    measurementId: 'G-JT77N40Y9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCuoR3JUIbhof1ks2IQEvljYKzX8URAc',
    appId: '1:306144619621:android:167b4d1b0789435fb5ea8c',
    messagingSenderId: '306144619621',
    projectId: 'ezblog-e46a4',
    storageBucket: 'ezblog-e46a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC28SjWqVA_9stQDCr9jSP3U6GWrbxs2cQ',
    appId: '1:306144619621:ios:c14b22bbc3d6bf51b5ea8c',
    messagingSenderId: '306144619621',
    projectId: 'ezblog-e46a4',
    storageBucket: 'ezblog-e46a4.appspot.com',
    iosBundleId: 'com.example.ezblog',
  );
}
